-- 1
SELECT NAME, AGE
FROM COURSE1
UNION
SELECT NAME, AGE
FROM COURSE2
ORDER BY AGE ASC;


-- 2
SELECT NAME, PHONE, AGE
FROM COURSE1
UNION ALL
SELECT NAME, PHONE, AGE
FROM COURSE2
ORDER BY AGE DESC;


-- 3
SELECT JOB, YEAR(HIREDATE), COUNT(JOB)
FROM EMP
GROUP BY JOB, YEAR(HIREDATE)
WITH ROLLUP;


-- 4
SELECT ENAME AS '이름', JOB AS '직무', DNAME AS '부서이름'
FROM EMP
JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'RESEARCH';


-- 5
SELECT ENAME AS '이름', DNAME AS '부서이름'
FROM EMP
JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME LIKE '%A%';


-- 6
SELECT ENAME AS '직원이름', DNAME AS '부서명',
       CONCAT(FORMAT(SAL, 0), '원') AS '급여'
FROM EMP
JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL >= 3000;


-- 7
SELECT EMPNO AS '직원번호',
       ENAME AS '직원이름',
       SAL * 12 AS '연봉',
       SAL * 12 + IFNULL(COMM, 0) AS '실급여',
       GRADE AS '급여등급'
FROM EMP
JOIN SALGRADE
ON SAL BETWEEN LOSAL AND HISAL
WHERE COMM IS NOT NULL
ORDER BY SAL * 12 + IFNULL(COMM, 0);


-- 8
SELECT DEPTNO AS '부서번호',
       ENAME AS '직원이름',
       SAL AS '급여',
       GRADE AS '급여등급'
FROM EMP
JOIN SALGRADE
ON SAL BETWEEN LOSAL AND HISAL
WHERE DEPTNO = 10;


-- 9
SELECT JOB AS '직무',
       ENAME AS '직원이름',
       DNAME AS '부서이름'
FROM EMP
JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'SALESMAN';


-- 10
SELECT EMP.DEPTNO AS '부서번호',
       DNAME AS '부서이름',
       ENAME AS '직원이름',
       EMP.SAL AS '급여',
       GRADE AS '급여등급'
FROM EMP
JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
JOIN SALGRADE
ON EMP.SAL BETWEEN LOSAL AND HISAL
WHERE EMP.DEPTNO IN (10, 20)
ORDER BY EMP.DEPTNO ASC, EMP.SAL DESC;


-- 11
SELECT IFNULL(ENAME, '없음') AS '이름',
       DEPT.DEPTNO AS '부서번호',
       DNAME AS '부서이름'
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT IFNULL(ENAME, '없음') AS '이름',
       DEPT.DEPTNO AS '부서번호',
       DNAME AS '부서이름'
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;


-- 12
SELECT ENAME AS '이름',
       DEPT.DEPTNO AS '부서번호',
       DNAME AS '부서이름'
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
ORDER BY ENAME ASC;


-- 13
SELECT ENAME AS '직원이름',
       COMM AS '커미션',
       DNAME AS '부서명',
       CITY AS '도시명'
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN LOCATIONS L
ON D.LOC_CODE = L.LOC_CODE
WHERE E.COMM IS NOT NULL;


-- 14
SELECT ENAME AS '이름',
       SAL AS '급여',
       GRADE AS '등급'
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN LOCATIONS L
ON D.LOC_CODE = L.LOC_CODE
JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE CITY = 'DALLAS';


-- 15
SELECT IFNULL(ENAME, '누구?') AS '이름',
       IFNULL(DEPT.DEPTNO, '어디?') AS '부서번호',
       IFNULL(DNAME, '어디?') AS '부서명'
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT IFNULL(ENAME, '누구?') AS '이름',
       IFNULL(DEPT.DEPTNO, '어디?') AS '부서번호',
       IFNULL(DNAME, '어디?') AS '부서명'
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;


-- 16
SELECT ENAME, HIREDATE, SAL
FROM EMP E
WHERE DEPTNO IN (
    SELECT D.DEPTNO
    FROM DEPT D
    JOIN LOCATIONS L
    ON D.LOC_CODE = L.LOC_CODE
    WHERE CITY = 'CHICAGO'
);


-- 17
SELECT ENAME, HIREDATE, DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN LOCATIONS L
ON D.LOC_CODE = L.LOC_CODE
WHERE CITY = 'CHICAGO';


-- 18
SELECT ENAME AS '이름',
       SAL * 12 + IFNULL(COMM, 0) AS '연봉',
       DNAME AS '부서명'
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN LOCATIONS L
ON D.LOC_CODE = L.LOC_CODE
WHERE CITY = 'DALLAS'
ORDER BY SAL * 12 + IFNULL(COMM, 0) DESC;


-- 19
SELECT CONCAT(COUNT(CITY), '명') AS '인원수'
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
JOIN LOCATIONS L
ON D.LOC_CODE = L.LOC_CODE
WHERE CITY = 'SEOUL';
